### ISSUE TITLE
[Feature Request] Cross-Dimension feature

### ISSUE THREAD

**Issue by DAmNRelentless** [Hexeption/RSInfinityBooster#1]
The infinity booster is a convenient way for all players.
Another nifty feature would be the ability to also access the network cross-dimensional without using the workaround of network transmitters and receivers.

To get this feature working, there are two ways I can think of:
1. add an additional card besides the infinity booster which adds cross-dimensional ability so you have to put both cards in
2. add a second infinity booster which also adds the cross-dimensional ability

In my opinion, the second option is the better one since you only need to put in one upgrade and since the cross-dimension upgrade depends on the infinity booster, it would make sense to merge both on one upgrade.
Also it would be more logical that the upgraded infinity booster depends on the normal infinity booster so you get logical recipes.

**Comment by brutalzinn** [comment]
i like the second option

**Comment by brutalzinn** [comment]
how i can help on it?
