### ISSUE TITLE
[Incompatible with RS pre-released version]

### ISSUE THREAD

**Issue by JuicyCosmos** [Hexeption/RSInfinityBooster#14]
Hello, I'm using the latest Refined Storage version from their Jenkins, which is RS 1.9.16 + 199. There is an incompatibity with RSInfinityBooster latest version 1.0 +6 for 1.16.5 where placing down a Controller or a Creative controller crashes the game, and trying to entering a world with a Controller already placed also crashes. I see this is very similar to issue #11 , but I'm currently using RSIB 1.0 + 6 and still experience the crash.
I know there had been a pre-release version available and is probably responsible for issue 11 in which RS 1.9.15 is used. But I'm using RS 1.9.16 which fixes a few bugs and the incompatibily with the controller is rendering RS unplayable. Is the unreleased version somehow been taken down from curseforge? I recall seeing that one day while browsing and now it's gone. I would like to have the newer version of RSIB and I tried to compile the code myself downloaded from your Github but to no avail.
I'll patiently wait if there's still work need to be done in order to fix the incompat or if there are more bugs you want to fix before pushing an update.  I'm just reporting since for me version 1.0 + 6 does not work (with RS 1.9.16) and I don't have access to RSIB 1.1.

**Comment by JuicyCosmos** [comment]
This is the crashlog, but I think it appears quite similar to that of issue #11's.
[Crashlog.txt](https://github.com/Hexeption/RSInfinityBooster/files/7447272/Crashlog.txt)

**Comment by Hexeption** [comment]
This has already been fixed but was taken down due to RS not releasing 1.9.16 on curseforge yet

**Comment by JuicyCosmos** [comment]
I don't think RS's gonna release on Curseforge soon but I might be wrong.  If possible could you send me the updated jar in private? I won't redistribute it since I'm only playing on single player and none of my friends play Minecraft. If not, I guess I'll have to use previous RS versions.
