### ISSUE TITLE
Interface stops working with Infinity Booster installed

### ISSUE THREAD

**Issue by Arch-Storm** [Hexeption/RSInfinityBooster#2]
When I insert the Infinity Booster my Interface, as well as my importers and exporters, immediately stop working. As soon as I take it out they work again. I have more than enough power, so that's not the problem. I'm using the latest Valhelsia 3 Modpack with your mod as an addition.

**Comment by Hexeption** [comment]
Can't replicate this issue

**Comment by Chunkimunki** [comment]
I can concur that this is happening to me as well - crafting grid is totally blank.
Wireless Transmitter goes dark until booster is removed and then lights back up.
Forge 36.0.42

**Comment by Arch-Storm** [comment]
> I can concur that this is happening to me as well - crafting grid is totally blank.
> Wireless Transmitter goes dark until booster is removed and then lights back up.
> Forge 36.0.42

That sounds more like you don't have enough power. The infinity booster uses 16000RF per tick. My grid etc works fine when using the booster.

**Comment by drstorm81** [comment]
> I can concur that this is happening to me as well - crafting grid is totally blank.
> Wireless Transmitter goes dark until booster is removed and then lights back up.
> Forge 36.0.42

Same issue here. It seems that it's related to RS power.
I had to increase internal buffer in my controller to make everything work.
It's not related to power supply, i can feed my controller up to 3Mrf/t (ultimate cables and induction matrix from Mekanism), still everything went dark with default buffer of 32000FE.

**Comment by Tommyg930** [comment]
> 
> 
> > I can concur that this is happening to me as well - crafting grid is totally blank.
> > Wireless Transmitter goes dark until booster is removed and then lights back up.
> > Forge 36.0.42
> 
> Same issue here. It seems that it's related to RS power.
> I had to increase internal buffer in my controller to make everything work.
> It's not related to power supply, i can feed my controller up to 3Mrf/t (ultimate cables and induction matrix from Mekanism), still everything went dark with default buffer of 32000FE.

How do you increase the buffer? I tried to find it in the official RS wiki and tries to google it but so far I haven't found anything making this mod unusable.

**Comment by Chunkimunki** [comment]
Just to corroborate the RS power findings a creative power cube attached to the controller still has the same problem. The controller is showing 1/2 energy.
RS config sadly not showing options for buffer capacity

**Comment by drstorm81** [comment]
> > > I can concur that this is happening to me as well - crafting grid is totally blank.
> > > Wireless Transmitter goes dark until booster is removed and then lights back up.
> > > Forge 36.0.42
> > 
> > 
> > Same issue here. It seems that it's related to RS power.
> > I had to increase internal buffer in my controller to make everything work.
> > It's not related to power supply, i can feed my controller up to 3Mrf/t (ultimate cables and induction matrix from Mekanism), still everything went dark with default buffer of 32000FE.
> 
> How do you increase the buffer? I tried to find it in the official RS wiki and tries to google it but so far I haven't found anything making this mod unusable.

It took me some time to find it. In 1.16 config is in:
- single player worlds - saves/*worldname*/serverconfig/refinedstorage-server.toml
- multiplayer server - *worldname*/serverconfig/refinedstorage-server.toml
In that file You need to increase 'capacity' in [controller]

**Comment by Arch-Storm** [comment]
It's getting even weirder for me now. I just tried using the infinity booster again yesterday and now it seems to work without any hiccups. I did not change a single thing in my power grid since the start of this issue.
My current power generation: Automatic carrot farm going into three mekanism crushers. Biofuel going into Pressurized Reaction Chamber which gets hydrogen from an electrolytic seperator. I am using a single Gas-Burning Generator with Ethylene which seems to work just fine with a few Efficiency Upgrades in the other machines. I didn't change anything regarding the controllers capacity. I also have no other machines connected to that power grid.

**Comment by Tommyg930** [comment]
> It took me some time to find it. In 1.16 config is in:
> 
>     * single player worlds - saves/_worldname_/serverconfig/refinedstorage-server.toml
> 
>     * multiplayer server - _worldname_/serverconfig/refinedstorage-server.toml
>       In that file You need to increase 'capacity' in [controller]

Ah ok, I thought people where somehow increasing the buffer ingame, not through the toml files. Thx!

**Comment by LegendarySkar** [comment]
I ran into this issue today and did some testing. 
The booster works fine with the creative controller.
With the normal controller it starts working as soon as you increase the capacity to double the consumption. 1 RF/t less and it's not working anymore. Strange thing is, even when the network seems to shut down completely, the wireless crafting grid still works fine. But importers, exporters, interfaces, crafters, etc. don't work.
A working theory from a discussion I had on discord is that Refined Storage doesn't check power consumption every tick, but rather every 2 ticks, according to my test.

Hope that helps, but I guess it's an issue with RS rather than this mod.
