### ISSUE TITLE
version 1.0+39 of 09/06/2024

### ISSUE THREAD

**Issue by jollyfish91** [Hexeption/RSInfinityBooster#37]
this version just crash my game when i try to join my world or at world creation and if i downgrade it works normally

**Comment by oldmooshie** [comment]
Seconding this. Crash report attached. 
[crash-2024-09-08_07.19.14-server.txt](https://github.com/user-attachments/files/16921995/crash-2024-09-08_07.19.14-server.txt)

**Comment by zrovihr** [comment]
same here.
RSInfinityBooster v1.20.1-1.0+39

**Comment by Hexeption** [comment]
look into this in the morning as I'm free
