### ISSUE TITLE
Crashes Grid System RF Power

### ISSUE THREAD

**Issue by Klouver0X** [Hexeption/RSInfinityBooster#9]
when I use dimension card and Range card it crashes the Grid to not be able to have enough power to point I have tried many mods with RF power to give it and it still crashes with among it sucking it dry of power. I even spent whole 2 weeks and 3 days trying to give enough power but it's not budging

**Comment by ItsJawn** [comment]
You need to increase the buffer of the Refined storage mod from what I found:

- single player worlds - saves/worldname/serverconfig/refinedstorage-server.toml
- multiplayer server - worldname/serverconfig/refinedstorage-server.toml
In that file You need to increase 'capacity' in [controller]

In the same folder you can decrease the usage of the infinity card. I halved it from my server to be sure and it works fine. Still a huge energy hog sadly.

**Comment by Klouver0X** [comment]
thank you for showing me this, I will no closed this issue if I can
